#student details

studentName = 'Arfath'
College = 'SHDC'
Course = 'BCA'
#student marks
marks = [82, 79, 93, 57, 77]
print()
print('=============================')
print('    STUDENT MARKS REPORT')
print('=============================')
print()
print(f'Name        : {studentName}')
print(f'College     : {College}')
print(f'Course      : {Course}')
print()
print()
print('Marks')
print()
print()
print(f'Subject 1   : {marks[0]}')
print(f'Subject 2   : {marks[1]}')
print(f'Subject 3   : {marks[2]}')
print(f'Subject 4   : {marks[3]}')
print(f'Subject 5   : {marks[4]}')
print()
print()
print(f'Total Subjects  : {len(marks)}')
print(f'Highest Marks   : {max(marks)}')
print(f'Lowest Marks    : {min(marks)}')
print(f'Total Marks     : {sum(marks)}')
print(f'Average Marks   : {sum(marks) / len(marks)}')
marks[2] = 88
print(marks)
marks.append(85)
print(marks)
marks.remove(79)
print(marks)
print()
print()
print('========================')
print('     FINAL REPORT       ')
print('========================')
print()
print()
print(f'Name        : {studentName}')
print()
print(f'College     : {College}')
print()
print(f'Course      : {Course}')
print()
print()
print(f'Final Marks  : {marks}')
print()
print()
print(f'Total Subjects  : {len(marks)}')
print()
print(f'Highest Marks   : {max(marks)}')
print()
print(f'Lowest Marks    : {min(marks)}')
print()
print(f'Total Marks     : {sum(marks)}')
print()
print(f'Average Marks   : {sum(marks) / len(marks)}')
